server.port=8080

# -----------------------------------------------------------------
# Configurações importadas do seu arquivo supabase-config.js original
# -----------------------------------------------------------------
supabase.url=https://ytrowyxkuemlqmiyfvll.supabase.co
supabase.key=sb_publishable_IayDBaQKREcn9UabWjWC5Q_jvU8Ys7Z

# Para envios de e-mail reais pelo JavaMailSender (Nodemailer do Java)
# spring.mail.host=smtp.gmail.com
# spring.mail.port=587
# spring.mail.username=seu_email@gmail.com
# spring.mail.password=sua_senha_de_aplicativo
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true
